### ISSUE TITLE
Put support link into error messages + generate an automated email message to developers

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#10]
This would enable users to email us and send us their data when they encounter an error. We could later use this information to create informative error messages for users.

**Comment by ybukhman** [comment]
Display a simple message to the user and send debugging information to developer

**Comment by thethirduniverse** [comment]
Hi Yury, I'm working on this issue right now. Where do you want this email be sent from? 

I know it is preferably from something like `noreply@gcat.glbrc.com`, which would be more official. But that would require some coordination with the person that is running the server, and frankly I'm not familiar with the process. If you prefer this way, I'll try to make it work.

An alternative method is that we can create a new Gmail account, something like `gcatadmin@gmail.com`. It would be more convenient to connect to Gmail and sent you the debug info from there.

Which way do you prefer?

**Comment by ybukhman** [comment]
I prefer the first method, as GCAT is maintained by GLBRC.  To get IT help in setting this up, please email helpdesk@glbrc.wisc.edu.  Please CC me on the message.

**Comment by thethirduniverse** [comment]
Cool, I'll contact them.
