### ISSUE TITLE
Make sure pre-inoculation data points are ignored

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#15]
Example: ACSH686 GWASv1 dataset.  If inoculation time point is set to 11 but points 1-10 are not explicitly ignored, it looks like GCAT's fitting algorithm still uses them as valid data.

**Comment by amangpt777** [comment]
Hi Yury, I am implementing it by setting all the points before inoculation time under points.to.remove
I will test the results and create a pull request by tomorrow hopefully. Let me know if you find any issues in this approach.

**Comment by ybukhman** [comment]
Sounds good to me!

**Comment by ybukhman** [comment]
Fixed by f99d0c0
