### ISSUE TITLE
Compute area under the curve from specified range of time points

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#3]
Peris: Could it be posible to implement a function in GCAT to get the
Area Under Curve (AUC) between an specified range of time to don't
include ranges were curve continues growing due to evaporation of the media?

All we need to do about evaporation is let user specify a time range for which to compute the AUC.

Peris's responses to my query of June 11, 2015:
> Minh is starting to work on the Area Under The Curve (AUC) computation
> in GCAT.   It is our understanding that you wanted to compute area under
> a specified range of points, i.e. the user will specify the beginning
> and ending time points for the computation.
  I agree with this.

> We are wondering if you want to compute AUC based on raw data or the
> fitted curve, or both.
As AUC is usually used as a summary of the three kinetic parameters (lag 
time, maximum growth rate and maximum OD), it is required to fit the 
curve first and after compute the AUC, in that way AUC will be related 
with the kinetic parameters.

> Also, does the user need to specify the beginning time point, or is it
> always going to be 0?
Well, you can implement by default T0 = 1st time point, but maybe the 
user want to change the initial time point to remove part of the curve 
that are not biological relevant.

**Comment by ybukhman** [comment]
Trac comment by Minh:

@TODO:
* Implement the UI.
* Integrate the UI from Rails with GCAT (R Code)
* Implement the function in GCAT (R Code)
* Draw 2 additional vertical lines closing the needed region, add the result onto the graph, and think up a way to mark the region. 

Pseudo-code for integration:
```
AUC <- function(input.well, a, b) {
    f <- function(x) well.eval(input.well, x)
    return (integrate(f, a, b))
}
```

**Comment by ForteGS** [comment]
From Peris: "don't include ranges were curve continues growing due to evaporation of the media?"

I'm not sure what he meant by that.

**Comment by ybukhman** [comment]
AUC computation has been implemented in the R back-end.
