### ISSUE TITLE
Remove all references to use.linear.param

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#44]

**Comment by thethirduniverse** [comment]
If I remove all reference to `use.linear.param`, including the one in `gcat.analysis.main` function call, it will give me this error:

`["Error in if (fit.par$v < 0.5 && abs(fit.par$v) < 2 * summary(fit)$parameters[\"v\",  ", " \n  missing value where TRUE/FALSE needed\n"]`

However if I add `user.linear.param = F` to the function call, I will not have this error. I'm confused that isn't this supposed to be handled by default parameter?

**Comment by ybukhman** [comment]
I guess we'll just leave ```use.linear.param = F``` in the gcat.analysis.main function call for now.  Maybe Aman can look at this later at some point.
