### ISSUE TITLE
Error Handling between Rails and R

### ISSUE THREAD

**Issue by thethirduniverse** [ybukhman/GCAT#47]
Originally R tries to do some fancy exception handling to signal Rails about the error. But that does not seem to work. 

In order to signal error, R need to return a single error message from gcat.anlysis.main(), so that length() of that value will be 1.

**Comment by amangpt777** [comment]
Hi Guanqing, I have fixed on R side and sent the pull request for the same. Let me know if you face any issues.

**Comment by thethirduniverse** [comment]
Thanks! I’ll take a look at it on Monday.

**Comment by ybukhman** [comment]
May need to do this again in the future for some of the lower-level functions
