### ISSUE TITLE
The email does not be sent out to the user

### ISSUE THREAD

**Issue by enhaixie** [ybukhman/GCAT#58]
see the attachment
![email_gcat](https://cloud.githubusercontent.com/assets/15270031/11723947/aa60985e-9f36-11e5-8ac7-9baca16fbc0c.PNG)

The email address enhai.xie@wisc.edu does NOT receive any emails about the error

**Comment by enhaixie** [comment]
QA

**Comment by thethirduniverse** [comment]
The email is supposed to be sent to Yury. And Yury can decide how to respond and handle the error. I think that is the correct behavior.

**Comment by ybukhman** [comment]
Yes, this is the correct behavior.  The user provides his/her email address so we would be able to contact them for follow up.  However, perhaps we should send a copy to the user as well, for their record?  We could implement this in the next version, if we think it’s a good idea.

**Comment by ybukhman** [comment]
Upon discussion with Enhai, I think we should get GCAT to send the user a receipt.  Something like "Thank you for contacting GCAT development team.  We shall investigate and get back to you as soon as we can."

**Comment by thethirduniverse** [comment]
That's a good idea. I'll implement that.

**Comment by ybukhman** [comment]
Fixed by d0733bad806a509d9c4cdb5c2dd55b3f2ff0c5dd
