### ISSUE TITLE
Multipal plate precess download file name

### ISSUE THREAD

**Issue by enhaixie** [ybukhman/GCAT#59]
see the attachment
![downloadfilename](https://cloud.githubusercontent.com/assets/15270031/11730482/13bb3452-9f5b-11e5-8c66-9eb79dfd5632.PNG)

It should save that file as multiplePlateAnalysis NOT singlePlateAnalysis.

It is a multi-pal plate process

**Comment by ybukhman** [comment]
Yes, I've noticed it too.  This is a bug.

**Comment by ybukhman** [comment]
Fixed by ca156af6dceb020ddb9cba1b8cfa60d8ec0a7d29
