### ISSUE TITLE
File hangs GCAT

### ISSUE THREAD

**Issue by ybukhman** [ybukhman/GCAT#66]
This file seems to hang GCAT.  The likely reason is that it has a lot of extra columns with nothing in them.  It works fine when those columns are removed.  Files like this should be detected as invalid and GCAT should generate an error.

**Comment by ybukhman** [comment]
See the problem input file in Testing\github_issue_files\066_File_hangs_GCAT

**Comment by ybukhman** [comment]
After hanging for a really long time, GCAT returned the following error message:
Error in gcat.fit.main(file.name = file.name, load.type = "csv", single.plate = single.plate, : Error in <gcat.load.data>: Error in data.frame(Plate.ID, Well, OD, Time) : arguments imply differing number of rows: 25248, 4308729 

The problem is that it took forever for GCAT to get to this point.

**Comment by amangpt777** [comment]
Hi Yury, I just verified that this issue has been fixed as per code change pushed yesterday for Issue9 ( 9089eca or https://github.com/ybukhman/GCAT/pull/68 ). We can close this bug.

**Comment by ybukhman** [comment]
Thanks!

**Comment by ybukhman** [comment]
Fixed in 9089eca
